
USER = 'shreyasus'
PASSWORD = '1234'
EMAIL = 'shreyasdobhal@gmail.com'

DRIVER_PATH = '/home/'+USER+'/Downloads/chromedriver'
REPLY_ONLY_LIST_PATH = '/home/'+USER+'/Desktop/HINT4/replyOnlyList.txt'
SLANG_WORDS_PATH = '/home/'+USER+'/Desktop/HINT4/slangWords.txt'
SLANG_WORDS_RESPONSE_PATH = '/home/'+USER+'/Desktop/HINT4/slangWordsResponse.txt'
MY_DOCS_LIST_PATH = '/home/'+USER+'/Desktop/HINT4/MyDocs/myDocsList.txt'
MY_DOCS_PATH = '/home/'+USER+'/Desktop/HINT4/MyDocs/'
HINT_PATH = '/home/'+USER+'/Desktop/HINT4/'
URL = 'file:///home/'+USER+'/Desktop/HINT4/chatbot.html' 
DOWNLOAD_PATH = '/home/'+USER+'/Downloads/'
SAVING_PATH = '/home/'+USER+'/Desktop/HINT4/'
START_PATH = '/home/'+USER+'/'
